name: linear_date_selector
description: "A lightweight and customizable Flutter widget for selecting dates in a horizontal or vertical linear list with support for disabled dates and custom UI."
version: 0.0.1
homepage: https://github.com/nandanmaiya21/linear_date_selector/
repository: https://github.com/nandanmaiya21/linear_date_selector/

environment:
  sdk: ^3.10.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
topics:
  - date
  - calendar
  - date-selector
  - widget
  - flutter-ui
  
platforms:
  android:
  ios:
  web:

flutter:
